In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv('Vehicle Maintenance- Service Records.csv')

In [3]:
x=dataset.iloc[:, [4,5,7,8]].values
y=dataset.iloc[:,15].values

In [4]:
print(x)
print(y)

[['petrol' 2017 10000 11400]
 ['petrol' 2017 10000 11453]
 ['petrol' 2017 10000 10706]
 ...
 ['diesel' 2016 100000 106788]
 ['diesel' 2016 100000 112576]
 ['diesel' 2016 100000 110757]]
[0 0 0 ... 1 1 1]


# Data Preprocessing

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'most_frequent')
imputer.fit(x[:,1:])
x[:,1:]=imputer.transform(x[:,1:])


In [6]:
print(x)

[['petrol' 2017 10000 11400]
 ['petrol' 2017 10000 11453]
 ['petrol' 2017 10000 10706]
 ...
 ['diesel' 2016 100000 106788]
 ['diesel' 2016 100000 112576]
 ['diesel' 2016 100000 110757]]


# Label Encoding


In [7]:
from sklearn.preprocessing import LabelEncoder


In [13]:
le0 = LabelEncoder()
x[:,0] = le4.fit_transform(x[:,0])

In [14]:
print(x)


[[1 1 10000 11400]
 [1 1 10000 11453]
 [1 1 10000 10706]
 ...
 [0 0 100000 106788]
 [0 0 100000 112576]
 [0 0 100000 110757]]


In [16]:
print(y)

[0 0 0 ... 1 1 1]


# Splitting Dataset into training set and Test set


In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2, random_state=0)

In [19]:
print(X_train)

[[0 0 80000 85743]
 [0 0 50000 50900]
 [0 0 100000 112722]
 ...
 [0 0 10000 9068]
 [0 0 30000 30012]
 [1 1 20000 20634]]


In [20]:
print(X_test)

[[1 1 10000 10654]
 [0 0 30000 31225]
 [0 0 80000 90624]
 [0 0 20000 21000]
 [0 0 100000 110757]
 [0 0 60000 61379]
 [0 0 40000 39236]
 [0 0 40000 41382]
 [0 0 60000 60322]
 [0 0 40000 40283]
 [1 1 40000 40283]
 [1 1 10000 11009]
 [0 0 30000 30257]
 [0 0 50000 50438]
 [0 0 40000 41098]
 [0 0 20000 22398]
 [0 0 10000 10003]
 [0 0 70000 71253]
 [0 0 70000 70753]
 [1 1 10000 10980]
 [1 1 50000 53909]
 [0 0 20000 19009]
 [1 1 80000 89233]
 [1 1 30000 31820]
 [0 0 20000 20657]
 [0 0 70000 70789]
 [1 1 50000 50034]
 [1 1 40000 42657]
 [1 1 60000 59262]
 [0 0 50000 49878]
 [0 0 70000 71580]
 [1 1 80000 88431]
 [0 0 30000 30382]
 [0 0 20000 20158]
 [0 0 20000 20243]
 [1 1 50000 50283]
 [0 0 60000 60909]
 [0 0 30000 30382]
 [1 1 20000 19423]
 [0 0 40000 40722]
 [1 1 50000 50342]
 [0 0 30000 34543]
 [0 0 70000 70747]
 [1 1 30000 30545]
 [0 0 100000 128699]
 [1 1 70000 70976]
 [0 0 40000 40368]
 [1 1 60000 60632]
 [0 0 40000 43298]
 [0 0 20000 20453]
 [1 1 60000 60347]
 [0 0 10000 11028]
 [0 0 70

# Feature Scaling 


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [25]:
print(X_train)

[[-0.88081125 -0.88081125  1.39872499  1.51509915]
 [-0.88081125 -0.88081125  0.18593457  0.16845176]
 [-0.88081125 -0.88081125  2.20725194  2.55781073]
 ...
 [-0.88081125 -0.88081125 -1.43111932 -1.44831353]
 [-0.88081125 -0.88081125 -0.62259237 -0.63884871]
 [ 1.13531701  1.13531701 -1.02685585 -1.00129911]]


In [26]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, Y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [29]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
cm = confusion_matrix(Y_test, y_pred)


In [30]:
print(cm)

[[84 73]
 [67  4]]


In [31]:
accuracy_score(Y_test,y_pred)

0.38596491228070173

In [38]:
result = model.predict(sc.transform([[1, 1, 15000, 11700]]))
if result == [0]:
    print('No need to chnage fuel filter')
else:
    print('Need to change the fuel filter')

No need to chnage fuel filter
